// Auto-generated by new-day tool. No edit required
// Year 2025

use anyhow::Result;

mod day01;
mod day02;
mod day03;
mod day04;
mod day05;
mod day07;
mod day08;
mod day09;
mod day10;
mod day11;


type DayEntry = (&'static str, fn() -> Result<()>);
pub const DAYS: &[DayEntry] =
&[
    ("1", day01::solve),
    ("2", day02::solve),
    ("3", day03::solve),
    ("4", day04::solve),
    ("5", day05::solve),
    ("7", day07::solve),
    ("8", day08::solve),
    ("9", day09::solve),
    ("10", day10::solve),
    ("11", day11::solve),
];
