// Auto-generated by new-day tool. No edit required
// Year 2025

use anyhow::Result;

mod day01;
mod day02;
mod day03;
mod day04;
mod day05;


type DayEntry = (&'static str, fn() -> Result<()>);
pub const DAYS: &[DayEntry] =
&[
    ("1", day01::solve),
    ("2", day02::solve),
    ("3", day03::solve),
    ("4", day04::solve),
    ("5", day05::solve),
];
