// Auto-generated by new-day tool. No edit required
// Year 2024

use anyhow::Result;

mod day01;

type DayEntry = (&'static str, fn() -> Result<()>);

pub const DAYS: &[DayEntry] =
&[
    ("1", day01::solve),
];
